### PR TITLE
fix wrath for enemies, move to abilities

### PR DESCRIPTION
**Pull request by white-haired-uncle**
I'm not convinced the changes to update_stats are even needed anymore, since the ability special is created if it doesn't exist when it is needed.

Creating the ability on demand also fixed the issue with enemies not being effected by wrath, at least when attacked with lesser lethargy.

I don't see any reason all of the wml setting unit.variables.wrath* can't be moved to [set_wrath_intensity], assuming we can't just get rid of the variables stuff outright.  If not, I should look at how the unit is passed so that we don't need to "unstore" twice.

Fueled by death appears to still only look at positive wrath.

Tested with whirlwind and greater underdraw (lesser lethargy).

See #751

### CODE REVIEW

**Comment by white-haired-uncle** [comment]
I'm not seeing any backward compatability issue when starting from beginning of scenario.  

If you loaded an old save with active wrath as weapon special I suspect it would remain until the end of the scenario (or longer for chapter5 and possibly spinoffs).  update_stats might clear that up.

**Comment by Dugy** [comment]
No, there would not be such a compatibility issue because the events providing the wrath decay behaviour would remain imprinted in the scenario code.

**Comment by white-haired-uncle** [comment]
Replaced all of the WML adjustments to unit.variables.wrath_intensity with add=/div= options to [set_wrath_intensity].

I'm still not convinced the unit.variables are needed, and I suspect setting unit.variables.wrath could be moved to  [set_wrath_intensity] (removing the need for an unstore_unit), but it's probably not necessary to optimize everything at this point, we've moved the specials to abilities, simplified the WML quite a bit, and fixed a couple things in the process.

fueled and at least one other that weren't considering negative wrath values should be fixed as a side effect.

tested with whirlwind and lesser lethargy.

**Comment by Dugy** [comment]
I really like your design.

Just a few implementation details:

1. The intensity is now set right in the ability or is it the one in the unit's `[variables]`? You seem to have the information duplicated in the two.
2. If it decays to zero, the ability may be removed.

The reason why I think it's better to keep the intensity in the unit's `[variables]` is that it would allow moving the declaration of wrath outside of lua, use a macro defining that ability as an argument to the WML tag, and reuse the code to create other abilities that can accumulate and decay. But I don't insist you do it this way, it's also possible to do it entirely in lua and use a callback to select the property that changes.

**Comment by white-haired-uncle** [comment]
> I really like your design.
> 
> Just a few implementation details:
> 
>     1. The intensity is now set right in the ability or is it the one in the unit's `[variables]`? You seem to have the information duplicated in the two.
> 

It is duplicated.  The way it was done before is the value in the variables was adjusted based on the previous value, and then the result was copied to [damage].  I just copied that (more or less) so it's effectively the same as before, but with one copy of [damage] instead of one per attack.  I don't see a point to this, which is why I was asking earlier if it needed to remain that way.
variables.wrath is the only thing that really "needs" to be in variables to serve as a filter for decay (and I'm not even sure that's true, I just didn't push the issue).

>     2. If it decays to zero, the ability may be removed.

I hadn't thought of that, and I didn't initially see a reason, but I do now.  The existence of the ability could serve as a semaphore, eliminating the need for variables.wrath.  I'm not sure, but it might even be more efficient to filter on an ability vs a unit.variable?

Then again, IMO the variables stuff was redundant before and it really isn't hurting anything so I can live with it.
 
> 
> The reason why I think it's better to keep the intensity in the unit's `[variables]` is that it would allow moving the declaration of wrath outside of lua

I don't see why having it only in [abilities][damage] would preclude accessing it in WML, though it's a little more work.

> , use a macro defining that ability as an argument to the WML tag, and reuse the code to create other abilities that can accumulate and decay. But I don't insist you do it this way, it's also possible to do it entirely in lua and use a callback to select the property that changes.

You lost me here.  Though as far as reusing the code, I think it would be pretty simple to change most of what is now [set_wrath_intensity] into something generic that took "wrath" as one possible input, if there was a second similar parameter that would grow/shrink/decay in the same way.

**Comment by Dugy** [comment]
> It is duplicated. The way it was done before is the value in the variables was adjusted based on the previous value, and then the result was copied to [damage]. I just copied that (more or less) so it's effectively the same as before, but with one copy of [damage] instead of one per attack. I don't see a point to this, which is why I was asking earlier if it needed to remain that way.

Keeping it in `[variables]` is superfluous now. It's not even needed for backwards compatibility because the WML code in events is saved with the mid-scenario save file.

>  The existence of the ability could serve as a semaphore, eliminating the need for variables.wrath. I'm not sure, but it might even be more efficient to filter on an ability vs a unit.variable?

Yes. I think the performance difference would be marginal, but it would avoid some clutter.

> Then again, IMO the variables stuff was redundant before and it really isn't hurting anything so I can live with it.

Originally, every unit had a latent_wrath weapon special on every attack, and the variable was just adjusting how they affected damage. There are better ways of doing that now.

> I don't see why having it only in [abilities][damage] would preclude accessing it in WML, though it's a little more work.

My idea was doing something like this:
```[set_stackable_ability]
  add=1
  id=$unit.id
  {ABILITY_WRATH}
```[/set_stackable_ability]

**Comment by white-haired-uncle** [comment]
I've removed [variables], everything is now under [abilities][damage] which is removed when not needed and serves as a filter for the decay event.

[set_stackable_ability] sounds like an interesting exercise, but AFAIK there is no other stackable ability right now and I've got other things to work on.

**Comment by Dugy** [comment]
Does it work with negative numbers (lethargy)?

**Comment by white-haired-uncle** [comment]
Now that you mention it, that's all I tested (whirlwind and lesser lethargy).  I went back and tested wrath, and a combination (wrath+whirlwind).  They work too.

**Comment by Dugy** [comment]
All right. I suppose that `add=` accepts negative numbers and will then work as subtract.

**Comment by white-haired-uncle** [comment]
It should, but there's also a sub=.

**Pull request merged**
