### PR TITLE
Delly is a female Preserved lich

### PR DESCRIPTION
**Pull request by Toranks**
Self explanatory

### CODE REVIEW

**Comment by Dugy** [comment]
I wonder if there is a language where _lich_ has a female form, but well, it's more correct this way.

**Comment by Toranks** [comment]
Lich>Liche on both forms, but "Preserved" has two forms on male and female. Preservado/Preservada

**Comment by Dugy** [comment]
This _liche_ can be grammatically both male and female depending on the context?

**Comment by Toranks** [comment]
> This _liche_ can be grammatically both male and female depending on the context?

Yes

**Comment by Dugy** [comment]
Fair enough.

**Pull request merged**
