### PR TITLE
fix missing dialog

### PR DESCRIPTION
**Pull request by white-haired-uncle**
Last night I picked up Lilith's Precious sword and smashed it to get a random gem.  Lilith was right there, she had to have seen me do it, and yet she said NOTHING.

### CODE REVIEW

**Comment by Discontinuum** [comment]
Should it still be visible if she's an ally?

**Comment by white-haired-uncle** [comment]
Yes.  She's mad because you broke one of her items.

It's kinda dumb, I know, but somebody will get a laugh out of it one day.

**Comment by Discontinuum** [comment]
I just thought you meant it when she's an enemy

**Comment by Dugy** [comment]
This is hilarious.

**Comment by Toranks** [comment]
Are these dialogs translatable?

**Comment by white-haired-uncle** [comment]
> Are these dialogs translatable?

Probably not.  Maybe they could be.  At first I used the example from the wiki

`wesnoth.fire("message", { speaker="narrator", message= _"Hello World!" })`

but it didn't like the underscore.  I thought about trying to use _="Hi, W" in the array of quotes, but I got lazy.

**Pull request merged**
