### PR TITLE
fix gold objectives

### PR DESCRIPTION
**Pull request by white-haired-uncle**
wish i knew how to combine these when using the web interface

### CODE REVIEW

**Comment by Dugy** [comment]
> wish i knew how to combine these when using the web interface

Are you submitting them by editing the code in the web interface?

**Comment by white-haired-uncle** [comment]
Yes.

**Comment by Dugy** [comment]
Then you can put multiple changes into the same pull request if you do this:
1. After making the first changes, mark the PR as draft
2. While you are viewing the branch of your PR, navigate to the code to make further changes
3. These changes will appear as separate commits in the same PR
4. When you think you've done enough of them, mark the PR as ready
5. I can squash the commits together when merging it

**Comment by white-haired-uncle** [comment]
perfect, thanks

**Pull request merged**
