### PR TITLE
Deprecated

### PR DESCRIPTION
**Pull request by white-haired-uncle**
tested where possible, though in a couple cases I can't find anything that would actually trigger the piece of code in question

### CODE REVIEW

**Comment by Dugy** [comment]
Where are these messages about deprecation shown?

**Comment by white-haired-uncle** [comment]
They show up on the console/log with debug enabled (I was using wesnoth -debug --log-debug=scripting/lua --no-log-to-file ).  Playing the tutorial is a simple way to trigger them.

**Comment by Dugy** [comment]
Aha... good to know.

**Comment by Toranks** [comment]
Don't update wesnoth.fire_event with wesnoth.game_events.fire in 1.16, or it won't work. It is a function of 1.17. The old version must be kept. The deprecated error only shows up in debug mode, a normal player won't see it, but with these changes a normal player in 1.16 will see a error of invalid function and it won't work.

**Comment by Toranks** [comment]
Don't update wesnoth.fire_event with wesnoth.game_events.fire in 1.16, or it won't work. It is a function of 1.17.6 and later only. The old version must be kept. The deprecated error only shows up in debug mode, a normal player won't see it, but with these changes a normal player in 1.16 will see the error and it won't work.

https://wiki.wesnoth.org/LuaAPI/wesnoth/game_events

**Comment by white-haired-uncle** [comment]
Ugh.  Good catch.  My test box defaulted to 1.17.

**Pull request merged**
