### PR TITLE
fix 'healing_filtering'

### PR DESCRIPTION
**Pull request by newfrenchy83**
like healing' abilities filtered in abilities_event.cfg, remove existent abilities before add new is only option valid.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
fix issue reported by @Discontinuum

**Comment by Dugy** [comment]
I am not sure if there isn't a better solution, see my comment at #431 .

**Comment by newfrenchy83** [comment]
i'm not familiar with lua formula and implementation in [filter_adjacent], i cannot repply, and fltering by type include burning abilites and unholybane, the only method for me, and what if you add a new abilites heals, remove the healing already present each time with id only(this is actually only attribute checkedin remove_ability)

**Comment by Discontinuum** [comment]
> I think ability_type_active=heals, which will work for any healing that is active at that point. That will include degeneration, though.

Can we check for the value, whether it's positive or not? I guess degenration abilities have negative value, don't they?

**Comment by Dugy** [comment]
Only by using a lua formula in the filter, I think.

**Comment by newfrenchy83** [comment]
another solution will be to let healing_{VALUE} but to add a heal with id=healing for filtering

**Pull request closed without merging**
