### PR TITLE
Basic translation to spanish

### PR DESCRIPTION
**Pull request by Toranks**
I'm going to translate the most visible things, name of units, abilities, traits and objects, the menu of items and crafting, and similar.

The po file is included. If I have to send it in another way, tell me and I will remove it from this PR.

When I see that it's okay, I'll change this from draft to final.

I've used the changed strings on https://github.com/Dugy/Legend_of_the_Invincibles/pull/450

### CODE REVIEW

**Comment by Toranks** [comment]
This can be merged too, since I'll regenerate the po file after you merge the other PR. Almost everything that appears in the UI is translated, and all autogenerated names, so it's usable right now, and can be pushed to the beta version in 1.17 addon server, for example, for people to test it.

**Comment by Dugy** [comment]
I am unable to review it at this point. I would need some scenario translated so that I could ask someone who speaks Spanish very well to assess independently how well are you translating it. Translating UIs and translating dialogues can be quite different.

Can you please translate some scenario before I merge it?

Oh, and I forgot to mention, please do include the .po file in the commits, it can be useful if someone else picks up your work, I can make the server ignore it.

**Comment by Toranks** [comment]
I had no intention of translating the dialogues and scenarios, it's too much work for me alone. But I can translate the tutorial or the context menu help FAQ.

**Comment by Dugy** [comment]
Ahaaa.... that is why you called it done at 17%.

**Comment by Toranks** [comment]
Made. Take a look and when you review it properly I'll put it back ready to merge. Remember I'm not done, I'll probably do 20-25%. I want it merged to continue with the new updated pot file on another PR.

**Comment by Toranks** [comment]
I send here a modification of the map to make it look better in full screen

**Comment by Toranks** [comment]
Is this still pending review? This can be merged. I've been pushing small updates just to get going, but I need to rebuild the pot file and continue from there.

**Comment by Dugy** [comment]
If you want this to be merged, can you please rebuild and upload the file with the latest strings? I think it's better to have more content translated than just the basics.

**Comment by Toranks** [comment]
Done

**Comment by Dugy** [comment]
Merged.

**Pull request merged**
