### PR TITLE
Buff weaked Efraim and Lethalia

### PR DESCRIPTION
**Pull request by Discontinuum**
Considering the discussion in #583, may propose this, buff them a bit (+5 hp, less xp to level on lower difficulties) and add one strike to basic faerie fire of Lethalia, that should prevent her from being stuck too much

### CODE REVIEW

**Comment by white-haired-uncle** [comment]
Tried this and liked it (normal diff).  I did get lucky with some decent item drops (of course, always happens when I'm testing).  Was concerned about the extra ffire attack affecting later scenarios, but they reset in S2 I believe.

**Comment by Toranks** [comment]
So this change is only for the first scenario and stats are changed on next scenario? An extra hit for Lethalia is devastating later on.

**Comment by Dugy** [comment]
This changes only the weakened type, that is transformed to the normal type in scenario 2.

**Comment by Dugy** [comment]
Well, I was assuming that this was resolved by white-haired-uncle's pull request that altered the first scenario.

Yes, I could update the server version, there wasn't much stuff going on here, so I would not interrupt anything probably.

**Comment by white-haired-uncle** [comment]
My change did not include this.  This one should be merged, IMO.

**Comment by Dugy** [comment]
Yes, but it made the scenario easier in different ways. Or do you mean that it was also assuming these changes would be made?

**Comment by Dugy** [comment]
All right.

**Pull request merged**
