### PR TITLE
update ktk

### PR DESCRIPTION
**Pull request by white-haired-uncle**
Update difficulty selection.  Needs better names (groupie, musician, rock star was the best I could come up with).

Update gold.  I don't like the bonus=yes, but no bonus (tell player there's early finish bonus, but it's 0).

Add [/unit_type] to end of most custom units.  I don't know that that comment at the end means, but it wouldn't load w/o this.

[advance] => [advancement] on one of the units.

Played on 1.16 okay.

### CODE REVIEW

**Review by Dugy — APPROVED** [review]

**Comment by Dugy** [comment]
>  Needs better names (groupie, musician, rock star was the best I could come up with).

Maybe __roadie__ for medium difficulty would be better, otherwise I like the suggested names.

> Update gold. I don't like the bonus=yes, but no bonus (tell player there's early finish bonus, but it's 0).

Yeah, that makes sense.

**Comment by white-haired-uncle** [comment]
yeah, roadie is what i meant for easy, not groupie.

**Comment by white-haired-uncle** [comment]
BTW, the drummer -- reference to Spoonman?

**Comment by Dugy** [comment]
> BTW, the drummer -- reference to Spoonman?

No, I don't know who is Spoonman.

**Comment by white-haired-uncle** [comment]
It's an old Soundgarden tune

"And all my friends are skeletons,
they beat the rhythm with their bones"

**Comment by Dugy** [comment]
Definitely a coincidence.

**Pull request merged**
