### PR TITLE
Merge unitdata library into master branch, step 1: unitdata.lua + testsuite

### PR DESCRIPTION
**Pull request by edwardspec**
First step of merging `unitdata.lua` into master branch.
See https://github.com/Dugy/Legend_of_the_Invincibles/issues/204#issuecomment-457998180 for details on step 1 and step 2.

Note: the library is NOT used anywhere yet. All changes in `stats.lua` and `items.lua` (which actually affect the game) were **excluded** from this branch (`unitdata-api-lib`). They can be found on `unitdata-api` branch.
They will be merged separately (as step 2 of the merge).

### CODE REVIEW

**Comment by Dugy** [comment]
I know you're still doing something around it, but I have some remarks:

- Please don't use points at the end of comments as long as the comments aren't several sentences long, it's not prose
- Why was the listing of AMLA effects removed from the `effects` function? My implementation of `stats.lua` depended on it, although it seems not to be merged into master yet. Why is that?

**Comment by edwardspec** [comment]
> Why was the listing of AMLA effects removed from the `effects` function?

They are still listed.
I replaced three loops (for advancements, items and other modifications) in `effects()` with one loop around all modifications. This covers the advancements too.

The test unlocks "Better with the sword" and "Harder to hit" on Efraim (Demigod) and he correctly gets the effects:
https://github.com/Dugy/Legend_of_the_Invincibles/blob/34404dc30adc45e9f5018cc9f8a4293224ed0dcf/tests/lua/unitdata.test.lua#L373
https://github.com/Dugy/Legend_of_the_Invincibles/blob/34404dc30adc45e9f5018cc9f8a4293224ed0dcf/tests/lua/unitdata.test.lua#L377
https://github.com/Dugy/Legend_of_the_Invincibles/blob/34404dc30adc45e9f5018cc9f8a4293224ed0dcf/tests/lua/unitdata.test.lua#L443-L472

**Comment by Dugy** [comment]
I was wrong.

But I still can't find where it lists traits.

**Comment by edwardspec** [comment]
Traits are modifications too.
This is also covered by the test.

**Comment by Dugy** [comment]
I see how it's done now. But why did you overwrite my code when my code was written in a way that was specifically prepared to be easily adaptable to the removal of equippable items and selectable advancements from the units' codes?

**Comment by edwardspec** [comment]
I rewrote it because its code is 3 times smaller now.
The implementation based on Lua arrays won't use this function at all. This function is only for WML-based storage.

**Comment by Dugy** [comment]
The lua implementation will be very similar to my code. I didn't want to write it twice. You didn't have to do it, but certainly, the code looks better now.

**Comment by edwardspec** [comment]
I'll provide the Lua implementation. (after stats.lua is tested and merged)

For the time being, we need both WML storage code and Lua storage code at the same time (we shouldn't overwrite the WML code), so that when someone loads an old save file, it can be read by WML storage code. (and converted into Lua storage format)

**Comment by edwardspec** [comment]
> Having the lua functions fall back to the WML implementation may be more difficult

```lua
if is_this_an_old_save() then
	loti.unit = wml_based_implementation
else
	loti.unit = lua_based_implementation
end
```

Here `is_this_an_old_save()` can, for example, check `wml_based_implementation.items()` of one unit with GEARED trait. If it returns anything, then this is an old save.

> Or you mean to write some code that will actually convert everything to the lua storage when old save file content is detected?

Can do this too. When the save file is loaded, we can check "is this an old save?" and then move items/advancements into the Lua storage. That's even better.

**Comment by edwardspec** [comment]
> I think you can just take my code and change a few lines

Just have a look at this **very preliminary** sketch.
Specifically at the code of `items()`, `advancements()` and `effects()`.

(all the heavy lifting is moved from `effects()` into utility functions `nextval()` and `effects_iter()`, which do trivial, easy-to-test things)

```lua
-- Sample storage (1 unit)
storage = {}
storage.items = {
	{ number = 100, effects = { "Effect 1", "Effect 2" } },
	{ number = 200, effects = { "Effect 3", "Effect 4" } },
	{ number = 300, effects = { "Effect 5", "Effect 6" } }
}
storage.advancements = {
	{ id = "fireball", effects = { "Effect 7", "Effect 8" } }
}
storage.other = {
	{ tag = "trait", name = "strong", effects = { "Effect 9", "Effect 10" } }
}

-- Utility function. Returns stateless version of next() for { number => value } array.
-- Example:
--	f = nextval({ 'a', 'b', 'c' })
--	print(f()) -- Prints "1 a"
--	print(f()) -- Prints "2 b"
local function nextval(array)
	local idx = 0
	return function()
		idx = idx + 1
		if array[idx] then
			return idx, array[idx]
		end
	end
end

function items() return ipairs(storage.items) end
function advancements() return ipairs(storage.advancements) end
function other() return ipairs(storage.other) end

-- Iterator over some of the effects.
-- Parameter: next_modification() - function that returns the next modification.
local function effects_iter(next_modification)
	local idx = 0
	local next_effect = function() end

	return function()
		while true do
			local _, effect = next_effect()
			if effect then
				idx = idx + 1
				return idx, effect -- Found another effect
			end

			-- Try next modification
			local _, modif = next_modification()
			if not modif then
				return -- Nothing more to return
			end

			next_effect = nextval(modif.effects)
		end
	end
end

function effects()
	local iterators = {
		effects_iter(nextval(storage.items)),
		effects_iter(nextval(storage.advancements)),
		effects_iter(nextval(storage.other))
	}

	local idx = 0
	return function()
		for _, candidate in ipairs(iterators) do
			local _, val = candidate()
			if val then
				idx = idx + 1
				return idx, val
			end
		end
	end
end

for idx, eff in effects() do
	print("Found effect #" .. idx .. ": " .. tostring(eff))
end
```

**Comment by Dugy** [comment]
Okay.

**Pull request merged**
