### PR TITLE
Redeem jump fixes

### PR DESCRIPTION
**Pull request by white-haired-uncle**
Changed INFERNO_SIDE in Doom Ford to valid team. Ref #555.

Moved code to get max redeem count for a redeem level to from [lua] to redeem.lua, and wrapped it in a wml tag.

Altered attack hits event for redeem to first check if redeemer.variables.redeem_level exists.  If not, fall back to previous method, and set that variable.  Then took this code and made it GET_REDEEM_LEVEL macro.  Also used this in the redeem level jump option.  Provides backward compatability with older saves for any situation I can think of.

Almost made a macro out of the redeem level jump options.  The only difference between the two is the target level.  Maybe some other time.  I probably tested the beginning of United close to 100 times, and I'm sick of it.

All known issues with redeem level jump option resolved and tested.  Ref #534 

I don't know why redeem.lua is also showing a change (blizzard desc) that's already done.  I did a sync, and created a whole new clean local repo that should very well be in sync.

### CODE REVIEW

**Comment by white-haired-uncle** [comment]
It's telling me "This branch has conflicts that must be resolved"  for utils/redeeming.cfg, and there's a button "Resolve conflicts", but I have no clue what it wants me to do from there.

**Comment by Dugy** [comment]
You've put two unrelated commits into the same feature branch, and the conflicts resulted in some luacheck problem.

If you fix the luacheck, I'll cherry-pick those commits into master to fix those strange issues you're having.

**Comment by white-haired-uncle** [comment]
I have absolutely no idea what is going on at this point.  When this is done, I'm nuking everything.  Twice.

**Comment by Dugy** [comment]
Maybe it's a space vs tabs thing? All the lua files have tabs, you have added spaces somewhere. Some languages' linters overreact to that because they need to compensate for their inability to spot type errors.

**Comment by white-haired-uncle** [comment]
Looks like my editor converts tabs to 4 spaces in *.lua and *.cfg.  I can disable that and just leave tabs as tabs for lua.

I tried to follow the Code Style directions on your main page.  I assume git/info/attributes is $repo/.git/info/attributes for me (linux), and git config -filter.tabspace.clean should be git config filter.tabspace.clean.  

And of course when I blasted everything and made a fresh new clone I forgot to do it again

**Comment by Dugy** [comment]
It looks like you fixed it finally. Can I merge it now or you want to do something else yet?

**Comment by white-haired-uncle** [comment]
Yes, can be merged.

I do have another redeem related issue which doesn't effect this.  I assume unrelated stuff should get separate commits (Doom Ford was a mistake), not sure that it matters with pull requests?

**Comment by Toranks** [comment]
I have downloaded LOTI at the present time, with this PR included, when starting a new scenario of the second part, already very advanced.
Just tested redeem, it works correctly and redemptions continue from the previous number.

**Pull request merged**
