### PR TITLE
Cleanup: remove obsolete #ifver blocks in all WML files

### PR DESCRIPTION
**Pull request by edwardspec**
A copying typo, same if/code twice.

### CODE REVIEW

**Comment by edwardspec** [comment]
To think of it, we might as well delete those backward compatibility #ifdef-s "for Wesnoth versions earlier than 1.13.1".
It's not like they are helpful when the new code is written with assumption "Wesnoth is at least version 14".

**Comment by Dugy** [comment]
Yeah, you can remove them all. I had written a C++ program to add them, there is a really huge quantity of them, so don't remove them manually in no case.

Please don't edit utils/stats.cfg, I am going to remove that file and it would cause commit conflicts I don't feel like resolving.

**Comment by edwardspec** [comment]
> Please don't edit utils/stats.cfg

Ok.

> there is a really huge quantity of them, so don't remove them manually in no case.

Found 748 of them. Will make a script to correctly remove them.

**Comment by edwardspec** [comment]
Removed all `#ifver` blocks for Wesnoth 1.11 and Wesnoth 1.13.

In case this is needed again in the future, here is the script I used: https://gist.github.com/edwardspec/84fb95acaa3bb5aab38236fece9e0207

**Comment by Dugy** [comment]
Is it ready for merge?

**Comment by edwardspec** [comment]
Yes, seems ok to me.
The only compatibility code left is in `utils/stats.cfg`, and also scripts in `ai/` directory (don't know if they are needed).

**Comment by Dugy** [comment]
I will be deleting utils/stats.cfg when I am done.

The ai directory isn't needed anymore if I recall correctly. All the stuff there is now part of 1.14.

**Comment by edwardspec** [comment]
I wonder if there was ever a pull request in history with more than 6000 deleted lines of code.

**Comment by Dugy** [comment]
Probably yes, obsolete codes are getting removed from projects. Revision systems ensure that they can be brought back.

**Pull request merged**
