### PR TITLE
Omitted translatable strings

### PR DESCRIPTION
**Pull request by Toranks**
Do I leave it as a draft? Possibly there are more such omissions throughout the campaign. Or do you prefer to fix its as I find them?

### CODE REVIEW

**Comment by Dugy** [comment]
Maybe it would be better if you left this as a draft so that it could be squashed before merging. If you need it merged for some reason, just ask.

**Comment by Toranks** [comment]
Thanks to wmlint, I have been able to verify that there are no more untranslated strings left, and it can be merged.

**Comment by Toranks** [comment]
Remember to rebuild all the po files after this

**Comment by Dugy** [comment]
All right. Merged.

**Pull request merged**
