### PR TITLE
Added Basic French Translation

### PR DESCRIPTION
**Pull request by Bafy78**
33 % completed, mostly UI elements and not dialogues.

### CODE REVIEW

**Comment by Bafy78** [comment]
I'm not sure if I placed the files in the right folder, but it works on my machine (when I place the files in the translations folder in the version of LoTi that I got from the add-ons server). I tried it in the dev version (this one, that's on github) but it didn't seem to work so idk.

**Comment by Dugy** [comment]
The translation seems to be in the right folder, are you sure you've placed the dev version at the right location? You could have misplaced it and kept using the version from the server.

**Comment by Dugy** [comment]
My French skills are rather rusty now, but I can still read French without issues, so I have read some parts of your translation to assess its quality. I must say that I liked it.

**Comment by Bafy78** [comment]
I just tried again and it works, so I don't know what I did wrong last time, but whatever.
Thanks for the praise about the quality of the translation :)

**Comment by Dugy** [comment]
Do you want me to merge it in this state or to wait until you translate more content?

**Comment by Bafy78** [comment]
I don't think I will continue translating in the near future. You can merge in this state.

**Comment by Dugy** [comment]
All right.

**Pull request merged**
