### PR TITLE
Replacing deprecated FOREACH macro with [foreach] tag

### PR DESCRIPTION
**Pull request by Discontinuum**
With this PR I start replacing deprecated FOREACH (which lacks scoping and overall not that fancy) to [foreach] tag, it's enough common so in order to reduce risks it would be bit-by-bit replacement

### CODE REVIEW

**Comment by Dugy** [comment]
Maybe it would be good to keep the iterating variable named `i` rather than the random names I was giving to avoid naming conflicts which should no longer be an issue. If you think it's not worth the risk of reintroducing bugs, I can merge it right now.

**Comment by Discontinuum** [comment]
I don't think renaming is worth it, if I miss something during renaming, it will be a bug and potentially a hidden one

**Comment by Dugy** [comment]
Okay. This is quite a risky change in a dynamically typed language.

**Comment by Discontinuum** [comment]
Yes, $this_item is possible, although we should  avoid iterating over it, coz https://github.com/wesnoth/wesnoth/issues/6305 (recently discovered after SXC and Era of Magic, which used this, got broken)

**Pull request merged**
