### PR TITLE
More item text adjustments

### PR DESCRIPTION
**Pull request by matsjoyce**
I should probably get on with some real work...

### CODE REVIEW

**Comment by Dugy** [comment]
Do you want commit access?

**Comment by matsjoyce** [comment]
Only if you trust me not to break things... :bowtie:

**Comment by Dugy** [comment]
Promise me that you will ask before making anything less usual.

**Comment by matsjoyce** [comment]
If I make a PR for any non-trivial changes, will that count?

**Comment by Dugy** [comment]
Yes. That's what I had in mind.

**Comment by matsjoyce** [comment]
OK, I will. Thanks for the invitation.

**Pull request merged**
