### PR TITLE
book6 -> book5

### PR DESCRIPTION
**Pull request by white-haired-uncle**

### CODE REVIEW

**Comment by Dugy** [comment]
Are you sure to want to keep this as a draft?

**Comment by white-haired-uncle** [comment]
Yes.  This is for typos and other minor corrections I find while I'm playing with difficulty.

**Comment by Dugy** [comment]
Okay, tell me when you're ready to merge it.

**Comment by white-haired-uncle** [comment]
Leaving it open didn't work.  Every time I make a change through the web interface the only option is to create a new branch.

**Comment by Dugy** [comment]
It works only if you navigate to the code while viewing your branch, that is, by having https://github.com/Dugy/Legend_of_the_Invincibles/tree/white-haired-typos in the address bar.

**Pull request merged**
