### PR TITLE
Typo on the Beautiful Child textdomain

### PR DESCRIPTION
**Pull request by Toranks**
Using the improved wmlgettext tool from the latest version 1.17.18, I have found several typos.

By the way, are these three separate campaigns still being updated or are they already obsolete?

### CODE REVIEW

**Comment by Dugy** [comment]
They are not obsolete, but they generally get less attention.

**Comment by Discontinuum** [comment]
TBC on the server right now is of an older broken version without LotI units advancements recently was noted on the forum https://forums.wesnoth.org/viewtopic.php?p=682529#p682529. Maybe KtK or AE have the same issue

In repo it was fixed in #435 but you didn't upload the fix to the addon server

**Comment by Dugy** [comment]
I could upload them, but would they work with the server version of LotI? Any idea if it's necessary to update LotI as well? I feel a bit uncertain about uploading it now when the Spanish translation by @Toranks is half-done.

**Comment by Discontinuum** [comment]
Personally I wouldn't mind to update LotI itself, there is a number of patches accumulated, but I would like probably to wait a bit, like a week or so, to make some more patches and to prepare my mods to the update

**Comment by Toranks** [comment]
The extra campaigns have another textdomain and I'm only translating wesnoth-loti. It does not matter if you update them before or after, since I am not translating the story and dialogues.

**Comment by Dugy** [comment]
> Personally I wouldn't mind to update LotI itself, there is a number of patches accumulated, but I would like probably to wait a bit, like a week or so, to make some more patches and to prepare my mods to the update

All right. Perhaps I'll force myself to add some code here myself like in the times of old.

**Pull request merged**
