### PR TITLE
Run "optipng -o7" on all PNG images (lossless optimization)

### PR DESCRIPTION
**Pull request by edwardspec**
This improves compression of PNG images, reducing their filesize.
This optimization is 100% lossless, they look _exactly_ as before.

### CODE REVIEW

**Comment by Dugy** [comment]
A similar thing was done some time ago. The algorithm seems to have become better since then, but the improvement is insignificant in many cases. A problem with this kind of change is that changes of binary files like this increase the size of the repository, which makes the repository somewhat harder to work with. Wesnoth's repository is several times larger than the game with source code and everything, making the github version quite annoying to work with.

Can you please exclude the images whose size was decreased by less than 10%?

**Comment by edwardspec** [comment]
Here we go. Still 178 files:
```
images/masks/illusion-break-mask-3.png (260 bytes = 10.73% decrease)
images/units/carcass.png (332 bytes = 41.87% decrease)
images/units/humans/prophet+female-defend.png (2814 bytes = 40.95% decrease)
images/units/humans/prophet+female-attack-sword.png (1974 bytes = 34.05% decrease)
images/units/humans/prophet+female.png (2480 bytes = 37.20% decrease)
images/units/humans/prophet+female-healing.png (2633 bytes = 38.41% decrease)
images/units/humans/prophet+female-moving.png (2537 bytes = 33.23% decrease)
images/units/monsters/skeletal-dragon.png (7377 bytes = 65.89% decrease)
images/units/monsters/skeletal-dragon-attack-jaw2.png (4976 bytes = 42.67% decrease)
images/units/monsters/skeletal-dragon-attack-claws2.png (5531 bytes = 36.53% decrease)
images/units/monsters/skeletal-dragon-attack-claws3.png (5747 bytes = 38.95% decrease)
images/units/monsters/skeletal-dragon-defend.png (5211 bytes = 31.41% decrease)
images/units/monsters/skeletal-dragon-attack-jaw1.png (4906 bytes = 39.03% decrease)
images/units/monsters/skeletal-dragon-attack-claws1.png (5911 bytes = 45.57% decrease)
images/units/enemies/ice-dragon-fangs.png (2072 bytes = 24.75% decrease)
images/units/enemies/black_army_bowman-defend.png (1028 bytes = 34.31% decrease)
images/units/enemies/black_army_mage-cast-2.png (1087 bytes = 35.22% decrease)
images/units/enemies/the_prince-defend.png (1176 bytes = 34.61% decrease)
images/units/enemies/fire-dragon-breath.png (2068 bytes = 24.50% decrease)
images/units/enemies/dark-dragon-fangs-n.png (2083 bytes = 26.11% decrease)
images/units/enemies/fire-dragon-fly.png (1982 bytes = 22.96% decrease)
images/units/enemies/black_army_bowman-melee-2.png (917 bytes = 28.63% decrease)
images/units/enemies/black_army_swordsman-attack-2.png (1363 bytes = 37.01% decrease)
images/units/enemies/dark-dragon-breath.png (2090 bytes = 24.70% decrease)
images/units/enemies/ice-dragon-fangs-n.png (2032 bytes = 25.63% decrease)
images/units/enemies/black_army_bowman-attack-3.png (1241 bytes = 38.93% decrease)
images/units/enemies/fire-dragon.png (2077 bytes = 24.67% decrease)
images/units/enemies/black_army_pikeman-defend.png (1246 bytes = 40.88% decrease)
images/units/enemies/the_prince-attack3.png (1388 bytes = 36.53% decrease)
images/units/enemies/dark-dragon-fangs.png (2121 bytes = 25.18% decrease)
images/units/enemies/dark-dragon-fly.png (2002 bytes = 23.43% decrease)
images/units/enemies/black_army_swordsman-defend.png (1441 bytes = 44.92% decrease)
images/units/enemies/black_army_bowman-attack-4.png (1177 bytes = 38.30% decrease)
images/units/enemies/black_army_swordsman.png (1693 bytes = 60.08% decrease)
images/units/enemies/ice-dragon-fly.png (1974 bytes = 22.82% decrease)
images/units/enemies/black_army_mage-melee.png (985 bytes = 28.97% decrease)
images/units/enemies/black_army_bowman.png (1369 bytes = 38.91% decrease)
images/units/enemies/fire-dragon-fangs-n.png (2076 bytes = 26.04% decrease)
images/units/enemies/black_army_bowman-melee-1.png (1070 bytes = 36.73% decrease)
images/units/enemies/the_prince-attack4.png (1429 bytes = 30.51% decrease)
images/units/enemies/the_prince-gun.png (1469 bytes = 45.08% decrease)
images/units/enemies/the_prince-attack2.png (1464 bytes = 30.40% decrease)
images/units/enemies/black_army_mage-cast-1.png (1130 bytes = 36.84% decrease)
images/units/enemies/dark-dragon.png (2102 bytes = 24.89% decrease)
images/units/enemies/ice-dragon.png (2055 bytes = 24.48% decrease)
images/units/enemies/the_prince-attack1.png (1501 bytes = 39.22% decrease)
images/units/enemies/black_army_bowman-attack-1.png (1260 bytes = 42.65% decrease)
images/units/enemies/black_army_mage-defend.png (1285 bytes = 43.01% decrease)
images/units/enemies/black_army_pikeman.png (1354 bytes = 44.64% decrease)
images/units/enemies/ice-dragon-breath.png (2044 bytes = 24.28% decrease)
images/units/enemies/the_prince.png (1836 bytes = 56.68% decrease)
images/units/enemies/black_army_pikeman-attack.png (1159 bytes = 40.60% decrease)
images/units/enemies/fire-dragon-fangs.png (2100 bytes = 24.99% decrease)
images/units/enemies/black_army_bowman-attack-2.png (1226 bytes = 39.18% decrease)
images/units/enemies/black_army_mage.png (1379 bytes = 45.66% decrease)
images/units/enemies/black_army_swordsman-attack-1.png (1556 bytes = 45.19% decrease)
images/units/undead/infernal-knight-defend-2.png (2127 bytes = 65.29% decrease)
images/units/undead/infernal-knight-defend-1.png (1829 bytes = 63.64% decrease)
images/units/undead/zombie-rider-attack-axe.png (1548 bytes = 34.62% decrease)
images/units/undead/infernal-knight-melee-attack-2.png (2111 bytes = 62.83% decrease)
images/units/undead/infernal-knight-crossbow-attack1.png (2029 bytes = 64.70% decrease)
images/units/undead/zombie-rider.png (2402 bytes = 56.04% decrease)
images/units/undead/infernal-knight.png (2208 bytes = 66.15% decrease)
images/units/undead/demilich-standing-3.png (1590 bytes = 38.48% decrease)
images/units/undead/infernal-knight-crossbow-defend.png (1960 bytes = 63.99% decrease)
images/units/undead/infernal-knight-lead-2.png (2654 bytes = 65.39% decrease)
images/units/undead/infernal-knight-melee-attack-1.png (2099 bytes = 64.39% decrease)
images/units/undead/infernal-knight-lead-1.png (2446 bytes = 65.68% decrease)
images/units/undead/infernal-knight-melee-attack-6.png (2017 bytes = 66.39% decrease)
images/units/undead/demilich-magic-1.png (1332 bytes = 35.09% decrease)
images/units/undead/infernal-knight-melee-attack-3.png (2151 bytes = 62.99% decrease)
images/units/undead/infernal-knight-crossbow.png (1976 bytes = 63.62% decrease)
images/units/undead/demilich-melee-1.png (1574 bytes = 38.14% decrease)
images/units/undead/demilich-defend.png (1291 bytes = 33.80% decrease)
images/units/undead/zombie-rider-attack-bite.png (2403 bytes = 52.94% decrease)
images/units/undead/demilich.png (1507 bytes = 37.69% decrease)
images/units/undead/demilich-standing-2.png (1535 bytes = 38.00% decrease)
images/units/undead/infernal-knight-melee-attack-4.png (1975 bytes = 61.18% decrease)
images/units/undead/infernal-knight-melee-attack-5.png (1639 bytes = 61.00% decrease)
images/units/undead/demilich-magic-2.png (1545 bytes = 38.80% decrease)
images/units/undead/infernal-knight-crossbow-attack2.png (1960 bytes = 63.84% decrease)
images/units/undead/demilich-melee-2.png (1636 bytes = 38.51% decrease)
images/units/undead/zombie-rider-defend.png (1537 bytes = 33.60% decrease)
images/misc/schedule-frozen.png (1124 bytes = 25.62% decrease)
images/misc/marksman-3.png (388 bytes = 44.80% decrease)
images/misc/drain-2.png (357 bytes = 11.04% decrease)
images/misc/schedule-fire.png (1448 bytes = 24.77% decrease)
images/misc/marksman-1.png (378 bytes = 45.93% decrease)
images/misc/schedule-snowstorm-night.png (690 bytes = 30.94% decrease)
images/misc/drain-3.png (355 bytes = 12.27% decrease)
images/misc/schedule-snowstorm-twilight.png (718 bytes = 21.09% decrease)
images/misc/firststrike-2.png (587 bytes = 23.42% decrease)
images/misc/marksman-2.png (392 bytes = 45.58% decrease)
images/misc/firststrike-3.png (550 bytes = 22.38% decrease)
images/misc/drain-1.png (492 bytes = 14.54% decrease)
images/misc/charge-1.png (445 bytes = 11.33% decrease)
images/misc/firststrike-1.png (1098 bytes = 42.57% decrease)
images/misc/schedule-snowstorm-day.png (830 bytes = 20.15% decrease)
images/misc/time/11dusk2.png (874 bytes = 10.22% decrease)
images/misc/time/7dawn2.png (760 bytes = 10.51% decrease)
images/terrain/hell/demonic_cemetery7.png (1923 bytes = 46.29% decrease)
images/terrain/hell/demonic_cemetery3.png (1088 bytes = 45.91% decrease)
images/terrain/hell/demonic_cemetery2.png (1010 bytes = 45.83% decrease)
images/terrain/hell/demonic_cemetery5.png (1133 bytes = 44.34% decrease)
images/terrain/hell/demonic_cemetery4.png (2228 bytes = 47.47% decrease)
images/terrain/hell/demonic_cemetery6.png (679 bytes = 45.03% decrease)
images/items/sword-fire-and-ice.png (239 bytes = 20.75% decrease)
images/maps/hell/23_Empire_of_Suffering.png (4983 bytes = 33.04% decrease)
images/maps/hell/34_Urias_Den.png (2651 bytes = 34.27% decrease)
images/maps/hell/04_Grim_Port.png (2349 bytes = 37.51% decrease)
images/maps/hell/25_Chambers_of_Oblivion.png (2774 bytes = 35.71% decrease)
images/maps/hell/06_Zhangors_Pass.png (7880 bytes = 31.89% decrease)
images/maps/hell/03_Shores_of_Abyss.png (5074 bytes = 32.79% decrease)
images/maps/hell/33_Pandemonium.png (8828 bytes = 31.33% decrease)
images/maps/hell/31_Bank_of_Ill_Luck.png (7078 bytes = 34.20% decrease)
images/maps/hell/05_Stygian_Caverns.png (3843 bytes = 38.03% decrease)
images/maps/hell/28_Twilit_Fortress.png (2227 bytes = 35.27% decrease)
images/maps/hell/09_Infernal_Narrows.png (3390 bytes = 39.39% decrease)
images/maps/hell/08_Doom_Ford.png (5728 bytes = 36.53% decrease)
images/maps/hell/26_Filthy_Keep.png (2162 bytes = 35.68% decrease)
images/maps/hell/29_Wicked_Barony.png (5455 bytes = 32.02% decrease)
images/maps/hell/32_Domain_of_Disaster.png (6738 bytes = 33.14% decrease)
images/maps/hell/24_Island_of_Atrocity.png (3620 bytes = 37.17% decrease)
images/maps/hell/14_Foul_Pits.png (1947 bytes = 35.92% decrease)
images/maps/hell/13_Dominion_of_Evil_Terror.png (3937 bytes = 36.41% decrease)
images/maps/hell/16_Sinful_Caves.png (3663 bytes = 36.14% decrease)
images/maps/hell/01_Transporting_Facility.png (6361 bytes = 33.84% decrease)
images/maps/hell/02_Tunnels_of_Cruelty.png (2832 bytes = 38.94% decrease)
images/maps/hell/20_Unholy_Realm.png (4586 bytes = 35.12% decrease)
images/maps/hell/l10n/de/23_Empire_of_Suffering.png (5061 bytes = 35.04% decrease)
images/maps/hell/l10n/de/34_Urias_Den.png (2724 bytes = 33.99% decrease)
images/maps/hell/l10n/de/04_Grim_Port.png (2450 bytes = 36.69% decrease)
images/maps/hell/l10n/de/25_Chambers_of_Oblivion.png (3148 bytes = 41.76% decrease)
images/maps/hell/l10n/de/06_Zhangors_Pass.png (8128 bytes = 32.79% decrease)
images/maps/hell/l10n/de/03_Shores_of_Abyss.png (5558 bytes = 35.13% decrease)
images/maps/hell/l10n/de/33_Pandemonium.png (8496 bytes = 31.28% decrease)
images/maps/hell/l10n/de/31_Bank_of_Ill_Luck.png (7169 bytes = 36.79% decrease)
images/maps/hell/l10n/de/05_Stygian_Caverns.png (2322 bytes = 39.08% decrease)
images/maps/hell/l10n/de/28_Twilit_Fortress.png (2471 bytes = 38.36% decrease)
images/maps/hell/l10n/de/09_Infernal_Narrows.png (3103 bytes = 40.12% decrease)
images/maps/hell/l10n/de/08_Doom_Ford.png (5806 bytes = 35.58% decrease)
images/maps/hell/l10n/de/26_Filthy_Keep.png (1785 bytes = 36.93% decrease)
images/maps/hell/l10n/de/29_Wicked_Barony.png (5264 bytes = 32.31% decrease)
images/maps/hell/l10n/de/32_Domain_of_Disaster.png (6913 bytes = 34.77% decrease)
images/maps/hell/l10n/de/24_Island_of_Atrocity.png (2962 bytes = 36.74% decrease)
images/maps/hell/l10n/de/14_Foul_Pits.png (1870 bytes = 35.71% decrease)
images/maps/hell/l10n/de/13_Dominion_of_Evil_Terror.png (3680 bytes = 36.44% decrease)
images/maps/hell/l10n/de/16_Sinful_Caves.png (2097 bytes = 39.02% decrease)
images/maps/hell/l10n/de/01_Transporting_Facility.png (6448 bytes = 35.74% decrease)
images/maps/hell/l10n/de/02_Tunnels_of_Cruelty.png (2051 bytes = 37.11% decrease)
images/maps/hell/l10n/de/20_Unholy_Realm.png (4372 bytes = 34.15% decrease)
images/maps/hell/l10n/de/21_Tormentors_Burrow.png (2807 bytes = 40.78% decrease)
images/maps/hell/l10n/de/18_Valley_of_Shattered_Souls.png (7583 bytes = 35.48% decrease)
images/maps/hell/l10n/de/27_Stronghold_of_Tears.png (2674 bytes = 41.79% decrease)
images/maps/hell/l10n/de/10_Fortress_of_Blackened_Dreams.png (5015 bytes = 36.60% decrease)
images/maps/hell/l10n/de/15_Plains_of_Chaos.png (9052 bytes = 33.78% decrease)
images/maps/hell/l10n/de/22_Where_the_Hatred_Grows.png (5760 bytes = 28.91% decrease)
images/maps/hell/l10n/de/12_Tainted_Shores.png (4305 bytes = 37.91% decrease)
images/maps/hell/l10n/de/07_Wasteland_of_Lost_Eternity.png (5152 bytes = 31.68% decrease)
images/maps/hell/l10n/de/17_River_Styx.png (5389 bytes = 31.75% decrease)
images/maps/hell/l10n/de/19_Land_of_Misery.png (4762 bytes = 36.67% decrease)
images/maps/hell/l10n/de/30_Nightmare_Cellar.png (3009 bytes = 33.82% decrease)
images/maps/hell/21_Tormentors_Burrow.png (2512 bytes = 37.35% decrease)
images/maps/hell/18_Valley_of_Shattered_Souls.png (7859 bytes = 35.13% decrease)
images/maps/hell/27_Stronghold_of_Tears.png (2768 bytes = 37.21% decrease)
images/maps/hell/10_Fortress_of_Blackened_Dreams.png (5234 bytes = 34.78% decrease)
images/maps/hell/15_Plains_of_Chaos.png (9007 bytes = 33.22% decrease)
images/maps/hell/22_Where_the_Hatred_Grows.png (5741 bytes = 27.75% decrease)
images/maps/hell/12_Tainted_Shores.png (5617 bytes = 36.01% decrease)
images/maps/hell/07_Wasteland_of_Lost_Eternity.png (5385 bytes = 32.98% decrease)
images/maps/hell/17_River_Styx.png (5364 bytes = 30.47% decrease)
images/maps/hell/19_Land_of_Misery.png (5196 bytes = 35.96% decrease)
images/maps/hell/30_Nightmare_Cellar.png (2325 bytes = 31.51% decrease)
images/maps/l10n/de/antediluvian_tunnels_map.png (33812 bytes = 15.00% decrease)
images/attacks/sword-fire-and-ice.png (858 bytes = 10.80% decrease)
images/attacks/sword-ice-only.png (1337 bytes = 17.50% decrease)
images/attacks/sword-fire-only.png (1110 bytes = 14.10% decrease)
images/merchant.png (1933 bytes = 22.25% decrease)
```

**Comment by edwardspec** [comment]
> A problem with this kind of change is that changes of binary files
> like this increase the size of the repository, which makes the repository
> somewhat harder to work with. 

Btw, the old binary files can be deleted from history via `git filter-branch`.
Large projects do this sometimes if it becomes a real problem.

**Comment by Dugy** [comment]
`git filter-branch` is a last resort tool. We don't want to get there.

**Pull request merged**
