### PR TITLE
items.lua: exclude orbs from list_regular(), they can't be unequipped

### PR DESCRIPTION
**Pull request by edwardspec**
Due to https://github.com/Dugy/Legend_of_the_Invincibles/pull/166#issuecomment-450121239

### CODE REVIEW

**Comment by Dugy** [comment]
There is still a check for the `silent=yes` key, which should play no role.

**Comment by edwardspec** [comment]
Removed silent check. Also removed those fake sorts, replaced them with id= key.

**Comment by edwardspec** [comment]
Rebased for cleaner Git history after merging.

**Comment by Dugy** [comment]
Be careful with the `id=` key, it is somehow used to prevent the same object from being applied more than once. In this case, it doesn't matter, but it could cause serious problems if it was used in the item system.

**Pull request merged**
