### PR TITLE
Nightmare Cellar

### PR DESCRIPTION
**Pull request by white-haired-uncle**
Created RARE_ITEM_TURN allowing setting of turn value for dropped item

I don't think I like optional arguments passed as an ordered list (to lua function).  If I were doing this from scratch, I think I'd rather pass a table with arguments declared explicitly.  But I don't have the XP to make that argument now, best to leave it alone.

Ref #527

### CODE REVIEW

**Comment by Discontinuum** [comment]
It accidentally reverted changed from #559

**Comment by Dugy** [comment]
Optional arguments for backwards compatibility can be a bad direction, but it's fine if it's just one.

**Comment by white-haired-uncle** [comment]
> It accidentally reverted changes from #559

I saw that, and I thought [6adba4d](https://github.com/Dugy/Legend_of_the_Invincibles/pull/564/commits/6adba4d78e93770fe4fdccbb3963fcb78271729e) would fix it.

Sorry, still learning.

**Comment by white-haired-uncle** [comment]
> Optional arguments for backwards compatibility can be a bad direction, but it's fine if it's just one.

There was one opt arg already.  I added a second.  That I don't like.

**Comment by Discontinuum** [comment]
Do we need the same kind of protection for Chapter 5 armouries? For other Inferno loot rooms?

**Comment by Dugy** [comment]
I think it might be useful.

**Comment by white-haired-uncle** [comment]
Looks like it for 3 storerooms in ch5 at least.  Working on it.

Surprised I never noticed this before.  I leave the room on turn 1 very often (switch rooms back and forth to move items around units in my autorecall list).

**Pull request merged**
