### PR TITLE
Avoid gold in item storage

### PR DESCRIPTION
**Pull request by edwardspec**
Possible solution for issue #188.

### CODE REVIEW

**Comment by edwardspec** [comment]
Question: do we know how many third-party addons use LotI as a dependency? (if any)

If any of them use INSERT_INTO_ITEMS, we might keep the ARRAY parameter (even if it's no longer used) to not break them.

**Comment by Dugy** [comment]
Add-ons that use LotI as a dependency are _The Beautiful Child,_ _Affably Evil_ and _Kill the King._ I don't think any of them uses that macro, but I am not completely certain.

**Comment by edwardspec** [comment]
They don't use this macro. (just checked)

**Comment by Dugy** [comment]
No problem then.

**Pull request merged**
