### PR TITLE
fix United/Transporting redeem upgrade

### PR DESCRIPTION
**Pull request by white-haired-uncle**
This will break backward compatibility with saves that don't have unit.variables.redeem_level.  I could put in a workaround, if it's not available when needed (redeem advancement), derive it from the attack special.

I don't know why that other commit is getting included here.  Maybe I'm not keeping local branch up to date with remote?

Ref: #534

### CODE REVIEW

**Comment by white-haired-uncle** [comment]
While looking at redeeming.cfg, I think I found a case where redeem_level might get reset to 1 on redeem advance.  I can't reproduce it, but I added a check to make sure it didn't happen.

**Comment by Dugy** [comment]
Can you please make it count the upgrades in case the redeem count variable is nil so that there is some backwards compatibility?

Also, there is some lua code that is repeating in multiple scenarios without much change, can this be a a function in `redeeming.lua` that would just be called from scenario code?

If you don't figure out how to remove the unrelated commits from the feature branch, I can cherry-pick the correct ones and squash them.

**Comment by white-haired-uncle** [comment]
I'm a little leery of counting upgrades because 
- the existing wml code and the existing lua code handle counting differently (absolute vs unique)
- there was an off-by-one issue with the wml code, at least in some places (N upgrades implies redeem (N+1), not redeem(N)).
- counting is dependent on lists of upgrades (currently separate lists) which could be error prone

I think the way to avoid these is just not depend on counting.

I can definitely put in a workaround for backward compatibility.  

That lua code does need to be centralized, and probably wrapped in wml tags.  But there's a lot I want to look further into in redeeming before I know exactly how (I think) it should look.

**Comment by Dugy** [comment]
I know the counting is inconsistent, the goal here is just to make sure an old save will not be less usable than necessary because the redeem level suddenly comes down from some high value to 1.

**Comment by Toranks** [comment]
How does the code finally work? Will you get the old redeem value as a variable to continue counting with the new method or will it reset to 0 but keeping advancements and skill level of redeem?

**Comment by white-haired-uncle** [comment]
> How does the code finally work with previous saves? Will you get the old redeem value as a variable to continue counting with the new method or will it reset to 0 but keeping advancements and skill level of redeem?

When it checks for the unit.variables.redee.m_level, if it doesn't find anything it uses the old method to find the level, and sets the variable.

The level, counts, achievements are all preserved, there's just an easier way to get the level.

**Comment by white-haired-uncle** [comment]
I forgot to close this. Superseded by #558

**Pull request closed without merging**
